### ISSUE TITLE
Auto restart daemon on crash

### ISSUE THREAD

**Issue by megamattron** [rtwomey/h12-monitor#1]
Thanks for making this project, it seems like almost exactly what we need. Unfortunately the daemon crashes after some number of lines for us and doesn't restart. Any tips on how we could make it restart if it crashed? The error looks like:

```
/usr/lib/ruby/1.9.1/openssl/buffering.rb:174:in `sysread_nonblock': end of file reached (EOFError)
```

Thanks!

**Comment by rtwomey** [comment]
@megamattron It's been a _long_ time since I looked at this project! One quick thought that comes to mind is to have the app automatically [respawn by using upstart](http://askubuntu.com/a/251581) (if using it). You might also consider using [daemon tools](http://cr.yp.to/daemontools.html).

You might also consider `rescue`ing on `EOFError` and making the script just loop around to re-open the connection and start again. That's probably a better approach. I'd accept a PR if you do.

Hope this helps.

**Comment by GAntoine** [comment]
Hi, I came across this issue recently and opened a PR that should fix it.
